### ISSUE TITLE
Check Message info

### ISSUE THREAD

**Issue by tt-vbalasubramanian** [Authentise/pytest-raises#5]
I really like this module where i dont have to write two tests one for positive and other for negative. But i would like to test the message of the Exception as well. Do you think is it possible? Can you help me with that?

**Comment by Lemmons** [comment]
This is certainly possible.  You are welcome to submit a PR to add this functionality (it should be pretty easy), or I can get to it when I have some time.

**Comment by Midnighter** [comment]
I'd also love to have this feature. Do you think you will have time in the near future? If not, can you give a hint where to best add this?

**Comment by Lemmons** [comment]
This feature has been added and is part of 0.7
